services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: backend-nodejs-event-dev
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: backend-nodejs-event-prod
    env_file:
      - .env
      - .env.production
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
    restart: always
